import type { SubjectCard, Tutor, Booking } from "./types";

export const SUBJECT_CARDS: SubjectCard[] = [
  {
    id: "maths",
    title: "Mathematics & Further Maths",
    description: "WAEC / JAMB / NECO exam preparation with proven past-question drilling methods.",
    icon: "Sigma",
    tutorCount: 48,
    accent: "from-indigo-500 to-blue-600",
  },
  {
    id: "english",
    title: "English & Literature",
    description: "Comprehension, essay writing, oral English, and literature-in-English coaching.",
    icon: "BookOpenText",
    tutorCount: 36,
    accent: "from-emerald-500 to-teal-600",
  },
  {
    id: "sciences",
    title: "Sciences",
    description: "Physics, Chemistry & Biology — practicals, theory, and lab-report guidance.",
    icon: "FlaskConical",
    tutorCount: 41,
    accent: "from-sky-500 to-indigo-600",
  },
  {
    id: "webdev",
    title: "Full-Stack Web Dev & Python",
    description: "Build real projects: JavaScript, React, Python, and backend fundamentals.",
    icon: "Code2",
    tutorCount: 29,
    accent: "from-violet-500 to-purple-600",
  },
  {
    id: "ai-data",
    title: "Generative AI & Data Skills",
    description: "Prompt engineering, machine learning basics, Excel, SQL & data analysis.",
    icon: "BrainCircuit",
    tutorCount: 22,
    accent: "from-amber-500 to-orange-600",
  },
  {
    id: "uiux",
    title: "UI/UX & Digital Design",
    description: "Figma, design systems, portfolio reviews, and product design fundamentals.",
    icon: "PenTool",
    tutorCount: 18,
    accent: "from-pink-500 to-rose-600",
  },
  {
    id: "exam-prep",
    title: "Exam Prep",
    description: "NECO, Post-UTME, SAT, and IELTS — strategy, mock tests, and timed practice.",
    icon: "GraduationCap",
    tutorCount: 33,
    accent: "from-blue-600 to-navy-700",
  },
  {
    id: "foundational",
    title: "Foundational Literacy & Numeracy",
    description: "Early-years reading, phonics, and primary numeracy for a strong head start.",
    icon: "Baby",
    tutorCount: 25,
    accent: "from-emerald-500 to-lime-600",
  },
];

export const STATES = [
  "Lagos (Lekki)",
  "Lagos (Ikeja)",
  "Lagos (Yaba)",
  "Abuja (Maitama)",
  "Abuja (Gwarinpa)",
  "Port Harcourt",
  "Ibadan",
  "Online / Remote",
];

export const SUBJECT_FILTERS = ["Maths", "Sciences", "Tech", "Languages", "Commercial", "Exam Prep"];

export const CURRICULA = ["Nigerian National", "British Cambridge", "American"];

export const TUTORS: Tutor[] = [
  {
    id: "t1",
    fullName: "Chiamaka Okafor",
    avatarUrl: "/images/tutor-01.jpg",
    headline: "WAEC & JAMB Mathematics Specialist",
    bio: "Chiamaka has spent 7 years helping SS2 & SS3 students conquer Mathematics and Further Maths for WAEC and JAMB. Her past-question drilling method has helped over 300 students raise their scores by at least 20%.",
    state: "Lagos",
    area: "Lekki",
    isOnline: false,
    isVerified: true,
    hourlyRate: 6500,
    currency: "NGN",
    yearsExperience: 7,
    curriculum: "Nigerian National",
    subjects: ["Mathematics", "Further Mathematics", "JAMB Prep"],
    subjectCategory: "Maths",
    ratingAvg: 4.9,
    totalReviews: 128,
    totalSessions: 540,
    idCardUploaded: true,
    degreeUploaded: true,
    availability: [
      { day: "Mon", start: "16:00", end: "19:00" },
      { day: "Wed", start: "16:00", end: "19:00" },
      { day: "Sat", start: "09:00", end: "13:00" },
    ],
    reviews: [
      { id: "r1", studentName: "Mrs. Adaobi (Parent)", rating: 5, comment: "My son's grade moved from C6 to A1 in one term. Extremely patient and structured.", createdAt: "2026-07-12" },
      { id: "r2", studentName: "Tobi O.", rating: 5, comment: "Explains calculus in a way that finally made sense to me.", createdAt: "2026-06-02" },
    ],
  },
  {
    id: "t2",
    fullName: "Tunde Bakare",
    avatarUrl: "/images/tutor-02.jpg",
    headline: "Physics & Chemistry Tutor — Cambridge IGCSE & WAEC",
    bio: "Tunde is a certified secondary school science teacher with a Masters in Physics Education. He blends real-world experiments with curriculum-aligned content for both Cambridge IGCSE and WAEC students.",
    state: "Abuja",
    area: "Maitama",
    isOnline: true,
    isVerified: true,
    hourlyRate: 8000,
    currency: "NGN",
    yearsExperience: 10,
    curriculum: "British Cambridge",
    subjects: ["Physics", "Chemistry", "IGCSE Combined Science"],
    subjectCategory: "Sciences",
    ratingAvg: 4.8,
    totalReviews: 94,
    totalSessions: 410,
    idCardUploaded: true,
    degreeUploaded: true,
    availability: [
      { day: "Tue", start: "17:00", end: "20:00" },
      { day: "Thu", start: "17:00", end: "20:00" },
      { day: "Sun", start: "14:00", end: "17:00" },
    ],
    reviews: [
      { id: "r1", studentName: "Hauwa M.", rating: 5, comment: "Breaks down difficult IGCSE physics topics so clearly.", createdAt: "2026-05-20" },
      { id: "r2", studentName: "Chidi E.", rating: 4, comment: "Very knowledgeable, sometimes sessions run a bit long (in a good way!).", createdAt: "2026-04-11" },
    ],
  },
  {
    id: "t3",
    fullName: "Ngozi Eze",
    avatarUrl: "/images/tutor-03.jpg",
    headline: "English Language & Literature Coach",
    bio: "Ngozi holds a BA in English from UNIPORT and has 5 years of experience preparing students for WAEC English, Literature-in-English, and oral communication skills.",
    state: "Port Harcourt",
    area: "Port Harcourt",
    isOnline: false,
    isVerified: true,
    hourlyRate: 4500,
    currency: "NGN",
    yearsExperience: 5,
    curriculum: "Nigerian National",
    subjects: ["English Language", "Literature-in-English", "Essay Writing"],
    subjectCategory: "Languages",
    ratingAvg: 4.7,
    totalReviews: 63,
    totalSessions: 220,
    idCardUploaded: true,
    degreeUploaded: false,
    availability: [
      { day: "Mon", start: "15:00", end: "18:00" },
      { day: "Fri", start: "15:00", end: "18:00" },
    ],
    reviews: [
      { id: "r1", studentName: "Ebere K.", rating: 5, comment: "My essay writing has improved tremendously.", createdAt: "2026-03-09" },
    ],
  },
  {
    id: "t4",
    fullName: "Emeka Nwachukwu",
    avatarUrl: "/images/tutor-04.jpg",
    headline: "Full-Stack Web Development & Python Mentor",
    bio: "Emeka is a software engineer turned tutor, teaching HTML/CSS/JS, React, and Python to beginners and intermediate learners with a project-based curriculum.",
    state: "Ibadan",
    area: "Ibadan",
    isOnline: true,
    isVerified: true,
    hourlyRate: 12000,
    currency: "NGN",
    yearsExperience: 6,
    curriculum: "American",
    subjects: ["JavaScript", "React", "Python", "Git & GitHub"],
    subjectCategory: "Tech",
    ratingAvg: 5.0,
    totalReviews: 77,
    totalSessions: 305,
    idCardUploaded: true,
    degreeUploaded: true,
    availability: [
      { day: "Tue", start: "18:00", end: "21:00" },
      { day: "Sat", start: "10:00", end: "14:00" },
      { day: "Sun", start: "10:00", end: "14:00" },
    ],
    reviews: [
      { id: "r1", studentName: "Daniel A.", rating: 5, comment: "Helped me ship my first React app. 10/10 mentor.", createdAt: "2026-08-01" },
      { id: "r2", studentName: "Grace I.", rating: 5, comment: "Patient, structured, and very responsive between sessions.", createdAt: "2026-07-18" },
    ],
  },
  {
    id: "t5",
    fullName: "Aisha Mohammed",
    avatarUrl: "/images/tutor-05.jpg",
    headline: "UI/UX & Digital Design Instructor",
    bio: "Aisha is a product designer at a fintech startup, teaching Figma, design systems, and portfolio building for aspiring designers across Nigeria — fully online.",
    state: "Online",
    area: "Remote",
    isOnline: true,
    isVerified: true,
    hourlyRate: 10000,
    currency: "NGN",
    yearsExperience: 4,
    curriculum: "American",
    subjects: ["UI/UX Design", "Figma", "Design Systems"],
    subjectCategory: "Tech",
    ratingAvg: 4.9,
    totalReviews: 51,
    totalSessions: 190,
    idCardUploaded: true,
    degreeUploaded: true,
    availability: [
      { day: "Wed", start: "19:00", end: "21:00" },
      { day: "Sat", start: "12:00", end: "16:00" },
    ],
    reviews: [
      { id: "r1", studentName: "Ifeoma N.", rating: 5, comment: "Landed my first design internship thanks to Aisha's portfolio reviews.", createdAt: "2026-06-29" },
    ],
  },
  {
    id: "t6",
    fullName: "Olumide Adeyemi",
    avatarUrl: "/images/tutor-06.jpg",
    headline: "Further Mathematics & JAMB Strategist",
    bio: "A former WAEC examiner with 15 years of classroom experience, Olumide specializes in getting students exam-ready with timed mock tests and strategy sessions.",
    state: "Lagos",
    area: "Yaba",
    isOnline: false,
    isVerified: true,
    hourlyRate: 7500,
    currency: "NGN",
    yearsExperience: 15,
    curriculum: "Nigerian National",
    subjects: ["Further Mathematics", "JAMB Prep", "Post-UTME Maths"],
    subjectCategory: "Exam Prep",
    ratingAvg: 4.95,
    totalReviews: 203,
    totalSessions: 860,
    idCardUploaded: true,
    degreeUploaded: true,
    availability: [
      { day: "Mon", start: "16:00", end: "20:00" },
      { day: "Thu", start: "16:00", end: "20:00" },
    ],
    reviews: [
      { id: "r1", studentName: "Blessing U.", rating: 5, comment: "Scored 289 in JAMB after 2 months with Mr. Olumide!", createdAt: "2026-02-14" },
      { id: "r2", studentName: "Samuel T.", rating: 5, comment: "Very strict but it works — highly recommend.", createdAt: "2026-01-30" },
    ],
  },
  {
    id: "t7",
    fullName: "Fatima Lawal",
    avatarUrl: "/images/tutor-07.jpg",
    headline: "IELTS, SAT & Post-UTME Exam Coach",
    bio: "Fatima has helped over 150 students prepare for international exams including IELTS and SAT, as well as Nigerian Post-UTME screening exams.",
    state: "Abuja",
    area: "Gwarinpa",
    isOnline: true,
    isVerified: false,
    hourlyRate: 9000,
    currency: "NGN",
    yearsExperience: 5,
    curriculum: "British Cambridge",
    subjects: ["IELTS", "SAT Prep", "Post-UTME"],
    subjectCategory: "Exam Prep",
    ratingAvg: 4.6,
    totalReviews: 38,
    totalSessions: 140,
    idCardUploaded: true,
    degreeUploaded: false,
    availability: [
      { day: "Tue", start: "09:00", end: "12:00" },
      { day: "Fri", start: "09:00", end: "12:00" },
    ],
    reviews: [
      { id: "r1", studentName: "Kemi A.", rating: 4, comment: "Great structure for IELTS speaking practice.", createdAt: "2026-05-05" },
    ],
  },
  {
    id: "t8",
    fullName: "David Okonkwo",
    avatarUrl: "/images/tutor-08.jpg",
    headline: "Generative AI, Data Analysis & SQL Mentor",
    bio: "David works as a data analyst and teaches practical AI tools, Excel, SQL, and the fundamentals of machine learning to career-changers and students alike.",
    state: "Online",
    area: "Remote",
    isOnline: true,
    isVerified: true,
    hourlyRate: 15000,
    currency: "NGN",
    yearsExperience: 6,
    curriculum: "American",
    subjects: ["Generative AI", "SQL", "Data Analysis", "Excel"],
    subjectCategory: "Tech",
    ratingAvg: 4.85,
    totalReviews: 44,
    totalSessions: 160,
    idCardUploaded: true,
    degreeUploaded: true,
    availability: [
      { day: "Wed", start: "18:00", end: "21:00" },
      { day: "Sun", start: "15:00", end: "19:00" },
    ],
    reviews: [
      { id: "r1", studentName: "Chinedu O.", rating: 5, comment: "Explained prompt engineering in a way my team could use immediately.", createdAt: "2026-08-22" },
    ],
  },
];

export const BOOKINGS: Booking[] = [
  {
    id: "b1",
    studentId: "demo_student",
    studentName: "Zainab Hassan",
    tutorId: "t1",
    tutorName: "Chiamaka Okafor",
    subject: "Mathematics",
    gradeLevel: "SS3",
    scheduledDate: "2026-10-06",
    startTime: "16:00",
    endTime: "17:30",
    status: "pending",
    sessionMode: "online",
    totalPrice: 9750,
    notes: "Focus on Trigonometry and Calculus before WAEC mock.",
    createdAt: "2026-10-01",
  },
  {
    id: "b2",
    studentId: "demo_student",
    studentName: "Daniel Afolabi",
    tutorId: "t4",
    tutorName: "Emeka Nwachukwu",
    subject: "React",
    gradeLevel: "Undergraduate",
    scheduledDate: "2026-10-04",
    startTime: "18:00",
    endTime: "19:30",
    status: "accepted",
    sessionMode: "online",
    meetingLink: "https://meet.google.com/abc-defg-hij",
    totalPrice: 18000,
    notes: "Continue building the portfolio project — state management module.",
    createdAt: "2026-09-28",
  },
  {
    id: "b3",
    studentId: "student-2",
    studentName: "Amara Chukwu",
    tutorId: "t6",
    tutorName: "Olumide Adeyemi",
    subject: "JAMB Prep",
    gradeLevel: "SS3",
    scheduledDate: "2026-09-25",
    startTime: "16:00",
    endTime: "18:00",
    status: "completed",
    sessionMode: "in_person",
    totalPrice: 15000,
    notes: "Full mock JAMB mathematics paper review.",
    createdAt: "2026-09-18",
  },
  {
    id: "b4",
    studentId: "demo_student",
    studentName: "Precious Edet",
    tutorId: "t2",
    tutorName: "Tunde Bakare",
    subject: "Physics",
    gradeLevel: "Year 11 (IGCSE)",
    scheduledDate: "2026-10-09",
    startTime: "17:00",
    endTime: "18:30",
    status: "pending",
    sessionMode: "online",
    totalPrice: 12000,
    notes: "Electromagnetism topic revision.",
    createdAt: "2026-10-01",
  },
  {
    id: "b5",
    studentId: "student-3",
    studentName: "Tobi Olawale",
    tutorId: "t1",
    tutorName: "Chiamaka Okafor",
    subject: "Further Mathematics",
    gradeLevel: "SS2",
    scheduledDate: "2026-09-20",
    startTime: "09:00",
    endTime: "10:30",
    status: "rejected",
    sessionMode: "in_person",
    totalPrice: 9750,
    notes: "Requested a Saturday morning outside listed availability.",
    createdAt: "2026-09-15",
  },
];

export function getTutorById(id: string): Tutor | undefined {
  return TUTORS.find((t) => t.id === id);
}
